<?php 
// $Id$

/**
 * @file
 * Extend Linkit with node links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_node_linkit_load_plugins($string) {
  drupal_add_js(drupal_get_path('modules', 'linkit_node') . '/linkit_node.js');
  $matches = array();
  
  // Get nodes
  $result = db_query_range("SELECT title, nid FROM {node} WHERE LOWER(title) LIKE LOWER('%%%s%%')", $string, 0, 10);
  while ($node = db_fetch_object($result)) {
    $matches['node'][linkit_autolist_val($node->title, 'Node', 'nid:'.$node->nid)] = linkit_autolist_list($node->title, 'Node');
  }

  return $matches;
}

/**
 * Implementation of hook_linkit_info_plugins().
 */
function linkit_node_linkit_info_plugins() {
  $return['linkit_node'] = array(
    'type' => 'node',
  );
  return $return;
}