<?php 
// $Id$

/**
 * @file
 * Extend Linkit with node links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_node_linkit_load_plugins($string) {
  $matches = array();
  
  $settings = variable_get('linkit_node', array());
  $fields = array('n.nid', 'n.title'); // default fields
  $where_status = "AND n.status = 1"; 
  
  if($settings['content_type']) {
    $fields[] = 'n.type';
  }
  if($settings['language']) {
    $fields[] = 'n.language';
  } 
  if($settings['status']) {
    $fields[] = 'n.status';
  }
  if($settings['show_unpublished']) {
    $where_status = '';
  }

  // Get nodes
  $result = db_query_range(db_rewrite_sql("SELECT %s FROM {node} n WHERE LOWER(n.title) LIKE LOWER('%%%s%%') %s"), implode(",", $fields), $string, $where_status, 0, 10);
  $i = 0;
  while ($node = db_fetch_object($result)) {
    $matches['node'][$i] = array(
      'title' => $node->title,
      'path' => 'internal:node/' . $node->nid,
      'information' => array(
        'type' => 'Node',
      ),
    );
 
    if($settings['nid']) {
      $matches['node'][$i]['information']['nid'] = $node->nid;
    } 
    if($settings['content_type']) {
      $matches['node'][$i]['information']['content type'] = $node->type;
    } 
    if($settings['language']) {
      $matches['node'][$i]['information']['language'] = $node->language ? $node->language : '-';
    } 
    if($settings['status']) {
      $matches['node'][$i]['information']['status'] = $node->status ? 'published' : 'unpublished';
    }

    $i++;
  }

  return $matches;
}

/**
 * Implementation of hook_linkit_info_plugins().
 */
function linkit_node_linkit_info_plugins() {
  $return['linkit_node'] = array(
    'type' => 'node',
  );
  return $return;
}