<?php 
// $Id$

/**
 * @file
 * Extend Linkit with node links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_node_linkit_load_plugins($string) {
  $matches = array();
  
  // Get nodes
  $result = db_query_range(db_rewrite_sql("SELECT n.nid, n.title FROM {node} n WHERE LOWER(n.title) LIKE LOWER('%%%s%%') AND n.status = 1"), $string, 0, 10);
  while ($node = db_fetch_object($result)) {
    $matches['node'][] = array(
      'title' => $node->title,
      'path' => 'internal:node/' . $node->nid,
      'information' => array(
        'type' => 'Node',
      ),
    );
  }

  return $matches;
}

/**
 * Implementation of hook_linkit_info_plugins().
 */
function linkit_node_linkit_info_plugins() {
  $return['linkit_node'] = array(
    'type' => 'node',
  );
  return $return;
}