<?php 
// $Id$

/**
 * @file
 * Extend Linkit with taxonomy links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_taxonomy_linkit_load_plugins($string) {
  drupal_add_js(drupal_get_path('modules', 'linkit_taxonomy') . '/linkit_taxonomy.js');
  $matches = array();
  
  // Get terms
  $result = db_query_range("SELECT name, tid FROM {term_data} WHERE LOWER(name) LIKE LOWER('%%%s%%')", $string, 0, 10);
  while ($term = db_fetch_object($result)) {
    $matches['taxonomy'][linkit_autolist_val($term->name, 'internal:taxonomy/term/' . $term->tid)] = linkit_autolist_list($term->name, 'Taxonomy');
  }
  return  $matches;
}