<?php 
// $Id$

/**
 * @file
 * Extend Linkit with taxonomy links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_taxonomy_linkit_load_plugins($string) {
  $matches = array();
  
  // Get terms
  $result = db_query_range(db_rewrite_sql("SELECT t.name, t.tid FROM {term_data} t WHERE LOWER(t.name) LIKE LOWER('%%%s%%')", 't', 'tid'), $string, 0, 10);
  while ($term = db_fetch_object($result)) {
    $matches['taxonomy'][] = array(
      'title' => $term->name,
      'path' => 'internal:taxonomy/term/' . $term->tid,
      'information' => array(
        'type' => 'Taxonomy',
      ),
    );
  }
  return  $matches;
}

/**
 * Implementation of hook_linkit_info_plugins().
 */
function linkit_taxonomy_linkit_info_plugins() {
  $return['linkit_taxonomy'] = array(
    'type' => 'taxonomy',
  );
  return $return;
}