<?php 

/**
 * @file
 * Extend Linkit with permissions.
 */

/**
 * Implementation of hook_perm().
 */
function linkit_permissions_permission() {
  $perms = array(
    'create all links' => array(
      'title' => t('Create all links'), 
      'description' => t('Can use all Linkt plugins'),
    ),
  );
  foreach (module_invoke_all('linkit_info_plugins') as $plugin) {
    $perms['create '. check_plain($plugin['type']) .' links'] = array(
      'title' => t('Create %type links', array('%type' => $plugin['type'])), 
      );
    };
  return $perms;
}