<?php 
// $Id$

/**
 * @file
 * Extend Linkit with user links.
 */


/**
 * Implementation of hook_linkit_load_plugins().
 */
function linkit_user_linkit_load_plugins($string) {
  $matches = array();

  // Get users
  $result = db_query_range("SELECT u.uid, u.name FROM {users} u WHERE LOWER(u.name) LIKE LOWER('%%%s%%') AND u.status = 1", $string, 0, 10);
  while ($user = db_fetch_object($result)) {
    $matches['user'][linkit_autolist_val($user->name, 'internal:user/' . $user->uid)] = linkit_autolist_list($user->name, 'User');
  }

  return $matches;
}

/**
 * Implementation of hook_linkit_info_plugins().
 */
function linkit_user_linkit_info_plugins() {
  $return['linkit_user'] = array(
    'type' => 'user',
  );
  return $return;
}